var items = [
]

var obstructions = [
  {
    "xPos":"1",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"2",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"3",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"4",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"5",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"6",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"7",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"8",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"9",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"10",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"11",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"12",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"13",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"14",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"15",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"16",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"17",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"18",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"19",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"20",
    "yPos":"13",
    "type":1,
  },
  {
    "xPos":"20",
    "yPos":"14",
    "type":1,
  },
  {
    "xPos":"20",
    "yPos":"15",
    "type":1,
  },
  {
    "xPos":"20",
    "yPos":"16",
    "type":1,
  },
  {
    "xPos":"20",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"21",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"22",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"23",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"24",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"25",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"26",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"27",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"28",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"28",
    "yPos":"18",
    "type":1,
  },
  {
    "xPos":"28",
    "yPos":"19",
    "type":1,
  },
  {
    "xPos":"28",
    "yPos":"20",
    "type":1,
  },
  {
    "xPos":"28",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"29",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"30",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"31",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"32",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"32",
    "yPos":"22",
    "type":1,
  },
  {
    "xPos":"32",
    "yPos":"23",
    "type":1,
  },
  {
    "xPos":"32",
    "yPos":"24",
    "type":1,
  },
  {
    "xPos":"32",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"33",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"34",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"35",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"36",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"37",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"38",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"39",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"40",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"25",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"24",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"23",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"22",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"20",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"19",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"18",
    "type":1,
  },
  {
    "xPos":"41",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"42",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"43",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"44",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"45",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"46",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"47",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"48",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"49",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"50",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"51",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"52",
    "yPos":"17",
    "type":1,
  },
  {
    "xPos":"52",
    "yPos":"18",
    "type":1,
  },
  {
    "xPos":"52",
    "yPos":"19",
    "type":1,
  },
  {
    "xPos":"52",
    "yPos":"20",
    "type":1,
  },
  {
    "xPos":"52",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"53",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"54",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"55",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"56",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"57",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"58",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"59",
    "yPos":"21",
    "type":1,
  },
  {
    "xPos":"60",
    "yPos":"21",
    "type":1,
  },
];

var eventList = [
  {
    "eventID":0,
    "eventString":"",
    "roomString":"",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":1,
    "eventString":"You found a bomb...Ouch!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":-1000,
  },
  {
    "eventID":2,
    "eventString":"You found a bomb...Ouch!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":-1000,
  },
  {
    "eventID":3,
    "eventString":"You found a bomb...Ouch!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":-1000,
  },
  {
    "eventID":4,
    "eventString":"You found a bomb...Ouch!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":-1000,
  },
  {
    "eventID":5,
    "eventString":"You found a bomb...Ouch!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":-1000,
  },
  {
    "eventID":6,
    "eventString":"You found an extra Life!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":500,
  },
  {
    "eventID":7,
    "eventString":"You found a cup of Starbs!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":750,
  },
  {
    "eventID":8,
    "eventString":"You found a cup of Dunkin'!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":750,
  },
  {
    "eventID":9,
    "eventString":"You found an extra Life!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":500,
  },
  {
    "eventID":10,
    "eventString":"You found an extra Life!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":500,
  },
  {
    "eventID":11,
    "eventString":"You found a PAR Can.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":1000,
  },
  {
    "eventID":12,
    "eventString":"You found a MacBook!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":13,
    "eventString":"You found an iMac!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":14,
    "eventString":"You found a free trial of Photoshop.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":5000,
  },
  {
    "eventID":15,
    "eventString":"You found a free trial of After Effects.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":5000,
  },
  {
    "eventID":16,
    "eventString":"You a Touch Designer license.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":5000,
  },
  {
    "eventID":17,
    "eventString":"You found a diamond deposit!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":6000,
  },
  {
    "eventID":18,
    "eventString":"You found a crystal deposit!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":6000,
  },
  {
    "eventID":19,
    "eventString":"You found an emerald deposit!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":6000,
  },
  {
    "eventID":20,
    "eventString":"You found a moving spotlight.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":2500,
  },
  {
    "eventID":21,
    "eventString":"You found a moving spotlight.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":2500,
  },
  {
    "eventID":22,
    "eventString":"You found a moving spotlight.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":2500,
  },
  {
    "eventID":23,
    "eventString":"You found a moving spotlight.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":2500,
  },
  {
    "eventID":24,
    "eventString":"You found a moving spotlight.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":2500,
  },
  {
    "eventID":25,
    "eventString":"You found a moving spotlight.",
    "roomString":"",
    "eventEffect":0,
    "eventScore":2500,
  },
  {
    "eventID":26,
    "eventString":"You found a quartz deposit!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":6000,
  },
  {
    "eventID":27,
    "eventString":"You found a ruby deposit!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":6000,
  },
  {
    "eventID":28,
    "eventString":"You found an obsidian deposit!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":6000,
  },
  {
    "eventID":29,
    "eventString":"You found a classic video game controller!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":20000,
  },
  {
    "eventID":30,
    "eventString":"You found the Swamp Cats logo!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":3000,
  },
  {
    "eventID":31,
    "eventString":"You found WorldStage!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":350000,
  },
  {
    "eventID":32,
    "eventString":"You found the timecode!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":2997,
  },
  {
    "eventID":33,
    "eventString":"You found a projector!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":34,
    "eventString":"You found an analog TV!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":500,
  },
  {
    "eventID":35,
    "eventString":"You found a Disguise License!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":5000,
  },
  {
    "eventID":36,
    "eventString":"You found a small lighting desk!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":2000,
  },
  {
    "eventID":37,
    "eventString":"You found a large lighting desk!",
    "roomString":"",
    "eventEffect":4000,
    "eventScore":0,
  },
  {
    "eventID":38,
    "eventString":"You found Terry Jackson! You should go talk to him!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":1000000,
  },
  {
    "eventID":39,
    "eventString":"You found a Source Four!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":6000,
  },
  {
    "eventID":40,
    "eventString":"You found an LED wash light!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":41,
    "eventString":"You found an LED wash light!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":42,
    "eventString":"You found an LED wash light!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":43,
    "eventString":"You found an LED wash light!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":44,
    "eventString":"You found an LED wash light!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":45,
    "eventString":"You found an LED wash light!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":46,
    "eventString":"You found an LED wash light!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":47,
    "eventString":"You found a sandwich! Yum!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":5000,
  },
  {
    "eventID":48,
    "eventString":"You found a super rare KitKat!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":500000,
  },
  {
    "eventID":49,
    "eventString":"You found pizza in space! Yum!!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":400000,
  },
  {
    "eventID":50,
    "eventString":"You found steak! Steakkkkkk!!!!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":600000,
  },
  {
    "eventID":51,
    "eventString":"You found sushi! Looks fresh!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":300000,
  },
  {
    "eventID":52,
    "eventString":"You found a popsicle! Brr!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":100000,
  },
  {
    "eventID":53,
    "eventString":"You found noodles! Eat your noodles!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":750000,
  },
  {
    "eventID":54,
    "eventString":"You found space waffles! Out of this world!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":600000,
  },
  {
    "eventID":55,
    "eventString":"You found a strawberry donut!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":56,
    "eventString":"You found a vanilla donut!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":57,
    "eventString":"You found a blue donut!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":58,
    "eventString":"You found a chocolate donut!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":59,
    "eventString":"You found a classic video game controller!",
    "roomString":"",
    "eventEffect":0,
    "eventScore":64000,
  },
  {
    "eventID":60,
    "eventString":"You found Space Ketamine.",
    "roomString":"Someone found Space Ketamine",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":61,
    "eventString":"You found X-Ray glasses!",
    "roomString":"Someone found X-Ray glasses!",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":62,
    "eventString":"You found the crab rave!",
    "roomString":"These crabs are having some kind of party...",
    "eventEffect":0,
    "eventScore":20000,
  },
  {
    "eventID":63,
    "eventString":"You found a can of red paint! Don't spill it...",
    "roomString":"Oops, someone spilled a can of red paint!",
    "eventEffect":0,
    "eventScore":2000,
  },
  {
    "eventID":64,
    "eventString":"You found a can of green paint! Don't spill it...",
    "roomString":"Oops, someone spilled a can of green paint!",
    "eventEffect":0,
    "eventScore":2000,
  },
  {
    "eventID":65,
    "eventString":"You found a can of blue paint! Don't spill it...",
    "roomString":"Oops, someone spilled a can of blue paint!",
    "eventEffect":0,
    "eventScore":2000,
  },
  {
    "eventID":66,
    "eventString":"You found a classic film reel.",
    "roomString":"Someone transported us back to cowboy times...",
    "eventEffect":0,
    "eventScore":5000,
  },
  {
    "eventID":67,
    "eventString":"You collected a Poke Ball.",
    "roomString":"Everyone became Pokemon...Strange?",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":68,
    "eventString":"Hide all layers? <YES>",
    "roomString":"Oh no, everyone became invisible!",
    "eventEffect":0,
    "eventScore":2000,
  },
  {
    "eventID":69,
    "eventString":"You found the object that hides all objects!",
    "roomString":"All the items became invisible?",
    "eventEffect":0,
    "eventScore":2000,
  },
  {
    "eventID":70,
    "eventString":"You found Nyan Cat",
    "roomString":"Nyaaaaaaaaan!!!!",
    "eventEffect":0,
    "eventScore":20000,
  },
  {
    "eventID":71,
    "eventString":"You found John Cena!",
    "roomString":"Why are there trumpets playing???",
    "eventEffect":0,
    "eventScore":20000,
  },
  {
    "eventID":72,
    "eventString":"You found a space taco!",
    "roomString":"Looks like it's Taco Tuesday!",
    "eventEffect":0,
    "eventScore":10000,
  },
  {
    "eventID":73,
    "eventString":"You found a bucket of rainbow paint!",
    "roomString":"It's like a bag of skittles in here.",
    "eventEffect":0,
    "eventScore":5000,
  },
  {
    "eventID":74,
    "eventString":"You activated a time warp!",
    "roomString":"Someone activated a time warp!",
    "eventEffect":0,
    "eventScore":5000,
  },
  {
    "eventID":75,
    "eventString":"You found the game's debug mode!",
    "roomString":"Is this the game's code?",
    "eventEffect":0,
    "eventScore":11111,
  },
  {
    "eventID":76,
    "eventString":"You found a can of hard seltzer.",
    "roomString":"In space, there are no laws, only claws.",
    "eventEffect":0,
    "eventScore":-5000,
  },
  {
    "eventID":77,
    "eventString":"This hotdog looks like it wants to dance?",
    "roomString":"Someone found that strange dancing hot dog.",
    "eventEffect":0,
    "eventScore":420000,
  },
  {
    "eventID":78,
    "eventString":"You found an intergalactic hitchiker.",
    "roomString":"Zoltar hungers!",
    "eventEffect":0,
    "eventScore":6666,
  },
  {
    "eventID":79,
    "eventString":"You found a magnet! Try not to touch the screen.",
    "roomString":"Someone messed up the colors on the screen!",
    "eventEffect":0,
    "eventScore":1000,
  },
  {
    "eventID":80,
    "eventString":"You found Lena! Meow Meow Meow",
    "roomString":"Someone found a kitty!",
    "eventEffect":0,
    "eventScore":1000000,
  },
  {
    "eventID":81,
    "eventString":"You found a magic mushroom?",
    "roomString":"The mushroom's effects changed the screen!",
    "eventEffect":0,
    "eventScore":42000,
  },
  {
    "eventID":82,
    "eventString":"You found a magic mushroom?",
    "roomString":"The mushroom's effects changed the screen!",
    "eventEffect":0,
    "eventScore":42000,
  },
  {
    "eventID":83,
    "eventString":"You found a magic mushroom?",
    "roomString":"The mushroom's effects changed the screen!",
    "eventEffect":0,
    "eventScore":42000,
  },
  {
    "eventID":84,
    "eventString":"You found a rare creature from the depths!",
    "roomString":"Someone found a strange sea creature!",
    "eventEffect":0,
    "eventScore":60000,
  },
  {
    "eventID":85,
    "eventString":"You found a blizzard!",
    "roomString":"It's.....Snowing? In Las Vegas?",
    "eventEffect":0,
    "eventScore":60000,
  },
  {
    "eventID":86,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":87,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":88,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":89,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":90,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":91,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":92,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":93,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":94,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":95,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":96,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":97,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":98,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
  {
    "eventID":99,
    "eventString":"You found an unimplemented item.",
    "roomString":"Someone found an unimplemented item",
    "eventEffect":0,
    "eventScore":0,
  },
]
  

module.exports = {
  obstructions,items,eventList,
}